#!/bin/bash

CYAN='\[\033[36m\]';
GREEN='\[\033[32m\]'
WHITE='\[\033[37m\]'
ENDCOLOR="\[\033[m\]"

# Use escape sequence to include cwd in the title bar
case $TERM in
  xterm*|rxvt*|screen*)
    TITLEBAR='\[\e]0;\w\a\]';
    ;;
  *)
    TITLEBAR='';
    ;;
esac

unset PROMPT_COMMAND
export PS1="$TITLEBAR[$CYAN\u$ENDCOLOR@$GREEN\h $WHITE\W$ENDCOLOR]\$ "
