backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;

shadow = true;

# shadow-radius = 12;
# shadow-offset-x = -9;
# shadow-offset-y = -9;

shadow-red = 0.24;
shadow-blue = 0.24;
shadow-green = 0.24;
shadow-opacity = 0.8;

shadow-exclude = [
  "class_g = 'i3-frame'",
];

fading = true;

fade-in-step = 0.02;
fade-out-step = 0.016;
fade-delta = 8;

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 1; focus = true; full-shadow = true; };
  popup_menu = { shadow = false; }
  dropdown_menu = { shadow = false; fade = false }
  utility = { shadow = false; }
};

blur:
{
  method = "dual_kawase";
  strength = 10;
};

blur-background: true;
