#!/usr/bin/env sh

active_window=$(xdotool getactivewindow 2>/dev/null)

if [ $? -eq 0 ]; then
  echo $(xprop -id ${active_window} WM_CLASS | awk '{print $4}' | cut -d'"' -f2)
else
  focus_window=$(xdotool getwindowfocus)
  echo $(xdotool getwindowname ${focus_window})
fi
