(require 'package)

(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))

(add-to-list 'package-archives
             '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/") t)

(package-initialize)
(when (not package-archive-contents)
    (package-refresh-contents))

;; Any variables, functions, or macros defined in this configuration
;; are "namespaced" with a prefix of ~tvjg/~. This is only a convention
;; for easily distinguishing between built-in functions and those
;; defined in this configuration or another package, and has no other
;; special significance.

;; Keep any Elisp files not installed from a package repository in the
;; vendor/ directory

;; TODO: Load vendor subdirectories
(defvar tvjg/vendor-directory (concat user-emacs-directory "site-lisp/use-package"))
(add-to-list `load-path tvjg/vendor-directory)

;; Init use-package
(eval-when-compile
  (require 'use-package))
(require 'bind-key)

;; https://github.com/purcell/exec-path-from-shell
(use-package exec-path-from-shell
  :ensure t
  :config
  (progn
    (when (memq window-system '(mac ns))
      (exec-path-from-shell-initialize))))

;; Keep temporary files in a separate directory
(defvar tvjg/ephemeral-directory "~/.emacs.tmp/")
(unless (file-exists-p tvjg/ephemeral-directory)
  (mkdir tvjg/ephemeral-directory))

;; Keep Eshell's temporary files out of the way
(setq eshell-directory-name (expand-file-name "eshell/" tvjg/ephemeral-directory))

;;Autosave and backup files (currently disabled) go in /tmp.
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))
(setq make-backup-files nil)

;; Keep settings generated by M-x customize outside VCS
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file 'noerror)

;; Load other initialization files
(mapc 'load (directory-files "~/.emacs.d/lisp" t "^[0-9]+.*\.el$"))

(provide 'init)
